# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import claude_agent_pb2 as claude__agent__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in claude_agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClaudeAgentServiceStub(object):
    """═══════════════════════════════════════════════════════════
    SERVICE DEFINITION
    ═══════════════════════════════════════════════════════════

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/claude.agent.v1.ClaudeAgentService/CreateSession',
                request_serializer=claude__agent__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=claude__agent__pb2.Session.FromString,
                _registered_method=True)
        self.GetSession = channel.unary_unary(
                '/claude.agent.v1.ClaudeAgentService/GetSession',
                request_serializer=claude__agent__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=claude__agent__pb2.Session.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/claude.agent.v1.ClaudeAgentService/ListSessions',
                request_serializer=claude__agent__pb2.ListSessionsRequest.SerializeToString,
                response_deserializer=claude__agent__pb2.ListSessionsResponse.FromString,
                _registered_method=True)
        self.DeleteSession = channel.unary_unary(
                '/claude.agent.v1.ClaudeAgentService/DeleteSession',
                request_serializer=claude__agent__pb2.DeleteSessionRequest.SerializeToString,
                response_deserializer=claude__agent__pb2.Empty.FromString,
                _registered_method=True)
        self.Chat = channel.stream_stream(
                '/claude.agent.v1.ClaudeAgentService/Chat',
                request_serializer=claude__agent__pb2.ChatRequest.SerializeToString,
                response_deserializer=claude__agent__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.SendPrompt = channel.unary_stream(
                '/claude.agent.v1.ClaudeAgentService/SendPrompt',
                request_serializer=claude__agent__pb2.SendPromptRequest.SerializeToString,
                response_deserializer=claude__agent__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.Interrupt = channel.unary_unary(
                '/claude.agent.v1.ClaudeAgentService/Interrupt',
                request_serializer=claude__agent__pb2.InterruptRequest.SerializeToString,
                response_deserializer=claude__agent__pb2.InterruptResponse.FromString,
                _registered_method=True)
        self.Compact = channel.unary_unary(
                '/claude.agent.v1.ClaudeAgentService/Compact',
                request_serializer=claude__agent__pb2.CompactRequest.SerializeToString,
                response_deserializer=claude__agent__pb2.CompactResponse.FromString,
                _registered_method=True)
        self.GenerateSummary = channel.unary_unary(
                '/claude.agent.v1.ClaudeAgentService/GenerateSummary',
                request_serializer=claude__agent__pb2.GenerateSummaryRequest.SerializeToString,
                response_deserializer=claude__agent__pb2.GenerateSummaryResponse.FromString,
                _registered_method=True)
        self.GetAuthStatus = channel.unary_unary(
                '/claude.agent.v1.ClaudeAgentService/GetAuthStatus',
                request_serializer=claude__agent__pb2.GetAuthStatusRequest.SerializeToString,
                response_deserializer=claude__agent__pb2.GetAuthStatusResponse.FromString,
                _registered_method=True)
        self.StartOAuth = channel.unary_unary(
                '/claude.agent.v1.ClaudeAgentService/StartOAuth',
                request_serializer=claude__agent__pb2.StartOAuthRequest.SerializeToString,
                response_deserializer=claude__agent__pb2.StartOAuthResponse.FromString,
                _registered_method=True)
        self.CompleteOAuth = channel.unary_unary(
                '/claude.agent.v1.ClaudeAgentService/CompleteOAuth',
                request_serializer=claude__agent__pb2.CompleteOAuthRequest.SerializeToString,
                response_deserializer=claude__agent__pb2.CompleteOAuthResponse.FromString,
                _registered_method=True)
        self.RefreshToken = channel.unary_unary(
                '/claude.agent.v1.ClaudeAgentService/RefreshToken',
                request_serializer=claude__agent__pb2.RefreshTokenRequest.SerializeToString,
                response_deserializer=claude__agent__pb2.RefreshTokenResponse.FromString,
                _registered_method=True)
        self.SetAccountCredentials = channel.unary_unary(
                '/claude.agent.v1.ClaudeAgentService/SetAccountCredentials',
                request_serializer=claude__agent__pb2.SetAccountCredentialsRequest.SerializeToString,
                response_deserializer=claude__agent__pb2.SetAccountCredentialsResponse.FromString,
                _registered_method=True)
        self.GetAccountStatus = channel.unary_unary(
                '/claude.agent.v1.ClaudeAgentService/GetAccountStatus',
                request_serializer=claude__agent__pb2.GetAccountStatusRequest.SerializeToString,
                response_deserializer=claude__agent__pb2.GetAccountStatusResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/claude.agent.v1.ClaudeAgentService/HealthCheck',
                request_serializer=claude__agent__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=claude__agent__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.SubmitAnswer = channel.unary_unary(
                '/claude.agent.v1.ClaudeAgentService/SubmitAnswer',
                request_serializer=claude__agent__pb2.SubmitAnswerRequest.SerializeToString,
                response_deserializer=claude__agent__pb2.SubmitAnswerResponse.FromString,
                _registered_method=True)
        self.GetPendingQuestion = channel.unary_unary(
                '/claude.agent.v1.ClaudeAgentService/GetPendingQuestion',
                request_serializer=claude__agent__pb2.GetPendingQuestionRequest.SerializeToString,
                response_deserializer=claude__agent__pb2.GetPendingQuestionResponse.FromString,
                _registered_method=True)


class ClaudeAgentServiceServicer(object):
    """═══════════════════════════════════════════════════════════
    SERVICE DEFINITION
    ═══════════════════════════════════════════════════════════

    """

    def CreateSession(self, request, context):
        """Session Lifecycle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request_iterator, context):
        """Bidirectional streaming for conversation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendPrompt(self, request, context):
        """Unary prompt (simpler API for single request/response)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Interrupt(self, request, context):
        """Control
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Compact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateSummary(self, request, context):
        """Session Summary - generates AI summary of session activity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuthStatus(self, request, context):
        """OAuth & Account Management
        Note: OAuth for Claude Code is managed by the CLI. These methods provide
        status checking and guidance for CLI-based authentication.
        Check CLI auth status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartOAuth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteOAuth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAccountCredentials(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitAnswer(self, request, context):
        """AskUserQuestion support
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPendingQuestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClaudeAgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=claude__agent__pb2.CreateSessionRequest.FromString,
                    response_serializer=claude__agent__pb2.Session.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=claude__agent__pb2.GetSessionRequest.FromString,
                    response_serializer=claude__agent__pb2.Session.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=claude__agent__pb2.ListSessionsRequest.FromString,
                    response_serializer=claude__agent__pb2.ListSessionsResponse.SerializeToString,
            ),
            'DeleteSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSession,
                    request_deserializer=claude__agent__pb2.DeleteSessionRequest.FromString,
                    response_serializer=claude__agent__pb2.Empty.SerializeToString,
            ),
            'Chat': grpc.stream_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=claude__agent__pb2.ChatRequest.FromString,
                    response_serializer=claude__agent__pb2.ChatResponse.SerializeToString,
            ),
            'SendPrompt': grpc.unary_stream_rpc_method_handler(
                    servicer.SendPrompt,
                    request_deserializer=claude__agent__pb2.SendPromptRequest.FromString,
                    response_serializer=claude__agent__pb2.ChatResponse.SerializeToString,
            ),
            'Interrupt': grpc.unary_unary_rpc_method_handler(
                    servicer.Interrupt,
                    request_deserializer=claude__agent__pb2.InterruptRequest.FromString,
                    response_serializer=claude__agent__pb2.InterruptResponse.SerializeToString,
            ),
            'Compact': grpc.unary_unary_rpc_method_handler(
                    servicer.Compact,
                    request_deserializer=claude__agent__pb2.CompactRequest.FromString,
                    response_serializer=claude__agent__pb2.CompactResponse.SerializeToString,
            ),
            'GenerateSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateSummary,
                    request_deserializer=claude__agent__pb2.GenerateSummaryRequest.FromString,
                    response_serializer=claude__agent__pb2.GenerateSummaryResponse.SerializeToString,
            ),
            'GetAuthStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuthStatus,
                    request_deserializer=claude__agent__pb2.GetAuthStatusRequest.FromString,
                    response_serializer=claude__agent__pb2.GetAuthStatusResponse.SerializeToString,
            ),
            'StartOAuth': grpc.unary_unary_rpc_method_handler(
                    servicer.StartOAuth,
                    request_deserializer=claude__agent__pb2.StartOAuthRequest.FromString,
                    response_serializer=claude__agent__pb2.StartOAuthResponse.SerializeToString,
            ),
            'CompleteOAuth': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteOAuth,
                    request_deserializer=claude__agent__pb2.CompleteOAuthRequest.FromString,
                    response_serializer=claude__agent__pb2.CompleteOAuthResponse.SerializeToString,
            ),
            'RefreshToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshToken,
                    request_deserializer=claude__agent__pb2.RefreshTokenRequest.FromString,
                    response_serializer=claude__agent__pb2.RefreshTokenResponse.SerializeToString,
            ),
            'SetAccountCredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAccountCredentials,
                    request_deserializer=claude__agent__pb2.SetAccountCredentialsRequest.FromString,
                    response_serializer=claude__agent__pb2.SetAccountCredentialsResponse.SerializeToString,
            ),
            'GetAccountStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountStatus,
                    request_deserializer=claude__agent__pb2.GetAccountStatusRequest.FromString,
                    response_serializer=claude__agent__pb2.GetAccountStatusResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=claude__agent__pb2.HealthCheckRequest.FromString,
                    response_serializer=claude__agent__pb2.HealthCheckResponse.SerializeToString,
            ),
            'SubmitAnswer': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitAnswer,
                    request_deserializer=claude__agent__pb2.SubmitAnswerRequest.FromString,
                    response_serializer=claude__agent__pb2.SubmitAnswerResponse.SerializeToString,
            ),
            'GetPendingQuestion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPendingQuestion,
                    request_deserializer=claude__agent__pb2.GetPendingQuestionRequest.FromString,
                    response_serializer=claude__agent__pb2.GetPendingQuestionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'claude.agent.v1.ClaudeAgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('claude.agent.v1.ClaudeAgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClaudeAgentService(object):
    """═══════════════════════════════════════════════════════════
    SERVICE DEFINITION
    ═══════════════════════════════════════════════════════════

    """

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/claude.agent.v1.ClaudeAgentService/CreateSession',
            claude__agent__pb2.CreateSessionRequest.SerializeToString,
            claude__agent__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/claude.agent.v1.ClaudeAgentService/GetSession',
            claude__agent__pb2.GetSessionRequest.SerializeToString,
            claude__agent__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/claude.agent.v1.ClaudeAgentService/ListSessions',
            claude__agent__pb2.ListSessionsRequest.SerializeToString,
            claude__agent__pb2.ListSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/claude.agent.v1.ClaudeAgentService/DeleteSession',
            claude__agent__pb2.DeleteSessionRequest.SerializeToString,
            claude__agent__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/claude.agent.v1.ClaudeAgentService/Chat',
            claude__agent__pb2.ChatRequest.SerializeToString,
            claude__agent__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/claude.agent.v1.ClaudeAgentService/SendPrompt',
            claude__agent__pb2.SendPromptRequest.SerializeToString,
            claude__agent__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Interrupt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/claude.agent.v1.ClaudeAgentService/Interrupt',
            claude__agent__pb2.InterruptRequest.SerializeToString,
            claude__agent__pb2.InterruptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Compact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/claude.agent.v1.ClaudeAgentService/Compact',
            claude__agent__pb2.CompactRequest.SerializeToString,
            claude__agent__pb2.CompactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/claude.agent.v1.ClaudeAgentService/GenerateSummary',
            claude__agent__pb2.GenerateSummaryRequest.SerializeToString,
            claude__agent__pb2.GenerateSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAuthStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/claude.agent.v1.ClaudeAgentService/GetAuthStatus',
            claude__agent__pb2.GetAuthStatusRequest.SerializeToString,
            claude__agent__pb2.GetAuthStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartOAuth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/claude.agent.v1.ClaudeAgentService/StartOAuth',
            claude__agent__pb2.StartOAuthRequest.SerializeToString,
            claude__agent__pb2.StartOAuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteOAuth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/claude.agent.v1.ClaudeAgentService/CompleteOAuth',
            claude__agent__pb2.CompleteOAuthRequest.SerializeToString,
            claude__agent__pb2.CompleteOAuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/claude.agent.v1.ClaudeAgentService/RefreshToken',
            claude__agent__pb2.RefreshTokenRequest.SerializeToString,
            claude__agent__pb2.RefreshTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAccountCredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/claude.agent.v1.ClaudeAgentService/SetAccountCredentials',
            claude__agent__pb2.SetAccountCredentialsRequest.SerializeToString,
            claude__agent__pb2.SetAccountCredentialsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccountStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/claude.agent.v1.ClaudeAgentService/GetAccountStatus',
            claude__agent__pb2.GetAccountStatusRequest.SerializeToString,
            claude__agent__pb2.GetAccountStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/claude.agent.v1.ClaudeAgentService/HealthCheck',
            claude__agent__pb2.HealthCheckRequest.SerializeToString,
            claude__agent__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitAnswer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/claude.agent.v1.ClaudeAgentService/SubmitAnswer',
            claude__agent__pb2.SubmitAnswerRequest.SerializeToString,
            claude__agent__pb2.SubmitAnswerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPendingQuestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/claude.agent.v1.ClaudeAgentService/GetPendingQuestion',
            claude__agent__pb2.GetPendingQuestionRequest.SerializeToString,
            claude__agent__pb2.GetPendingQuestionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
